version: "1"
services:
  strona-application-db:
    image: mysql
    environment:
      - MYSQL_DATABASE=defaultdb
      - MYSQL_ROOT_PASSWORD=AVNS_yxRXkW0iv0p1xJC6JvQ
  strona-application:
    image: rafalsobieraj/strona-application:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - strona-application-db
